### PR TITLE
Increase tick resolution from 250us to 1us

### PR DESCRIPTION
**Pull request by thomascobb**

### CODE REVIEW

**Comment by GDYendell** [comment]
The resolution of PVT time is 1/4 ms, will it just round to the nearest 1/4 now?

**Comment by thomascobb** [comment]
I misread the PMAC documentation, the resolution of PVT time is actually 1/4 us... The maximum move time is 4096 ms not 4096 s as I previously thought!

**Comment by GDYendell** [comment]
Oh yeah. I also misread it... "the specified time uses the move time register, and has a range of 0 to 4095.9998 milliseconds, with a resolution of ¼-microsecond"

I assume we don't need to go any more precise than 1us then?

**Comment by thomascobb** [comment]
I hope not!

**Pull request merged**
